### ISSUE TITLE
Make the code PEP8 compatible

### ISSUE THREAD

**Issue by asdfMaciej** [Charrod/csgoteambot#4]
The code works, but it could use some tidying. There are many tools online (for ex. pep8online.com) to help you with this task.

**Comment by Charrod** [comment]
Totally agree. It is difficult since some of the strings/ conditionals are just naturally very long. I will look into it! Thanks for the input.

**Comment by Charrod** [comment]
Improved PEP8 Compatibility in commit 4678228.
